sudo: required
language: generic
services:
  - docker
 
  # language: generic 

before_install:
  - docker build -t emmy/react -f Dockerfile.dev .

script:
  - docker run -e CI=true emmy/react npm run test -- --coverage
  